# Generated by Django 2.0.2 on 2020-04-21 13:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sub_theme', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assisted',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(blank=True, choices=[(0, 'Iniciada'), (1, 'Acabada')], default=0, verbose_name='status')),
                ('date_assisted', models.DateField(auto_now_add=True, verbose_name='Data que assistiu')),
            ],
            options={
                'verbose_name': 'Assistida',
                'verbose_name_plural': 'Assistidas',
            },
        ),
        migrations.CreateModel(
            name='Classes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=40, verbose_name='Título')),
                ('description', models.CharField(max_length=150, verbose_name='Descrição')),
                ('creation_date', models.DateField(auto_now_add=True, verbose_name='Data de criação')),
                ('slug', models.SlugField(verbose_name='slug')),
                ('link', models.CharField(default='', max_length=150, verbose_name='Link')),
                ('sub_theme', models.ForeignKey(on_delete=models.SET(0), to='sub_theme.Sub_theme')),
            ],
            options={
                'verbose_name': 'Aula',
                'verbose_name_plural': 'Aulas',
                'ordering': ['title'],
            },
        ),
        migrations.AddField(
            model_name='assisted',
            name='classe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assisted', to='classes.Classes', verbose_name='classe'),
        ),
        migrations.AddField(
            model_name='assisted',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assisted', to=settings.AUTH_USER_MODEL, verbose_name='user'),
        ),
        migrations.AlterUniqueTogether(
            name='assisted',
            unique_together={('user', 'classe')},
        ),
    ]
