# Generated by Django 2.0.2 on 2020-04-21 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('theme', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sub_theme',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Nome')),
                ('slug', models.SlugField(verbose_name='slug')),
                ('theme', models.ForeignKey(on_delete=models.SET(0), to='theme.Theme')),
            ],
            options={
                'verbose_name': 'Sub Tema',
                'verbose_name_plural': 'Sub Temas',
                'ordering': ['name'],
            },
        ),
    ]
